---
title: "Homework 2"
author: "Raleigh Goodwin, Kavya Mudiam, Vinita Vader, Zach Shroeder, Ann-Marie Barrett"
date: "2/27/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(colorspace)
library(ggplot2)
library(here)
library(janitor)
library(lubridate)
library(rio)
library(gt)

transit_cost <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-05/transit_cost.csv')

#install.packages("tidytuesdayR")
#transit_cost <- tidytuesdayR::tt_load(2021, week = 2)
crime = import(here("Data/crime.csv"), setclass = "tb_df") %>% 
  characterize() %>% 
  clean_names()

#install.packages("countrycode")
country_codes <- countrycode::codelist %>% 
  select(country_name = country.name.en, country = ecb)
```

# Question 1
```{r}
transit_cost <- left_join(transit_cost, country_codes, by = "country")

transit_cost_by_c <- transit_cost %>% 
  select(country_name, real_cost) %>% 
  drop_na() %>% 
  mutate(country_name = factor(country_name),
         real_cost = as.numeric(real_cost)) %>%
  drop_na() %>% 
  group_by(country_name) %>% 
  summarize(mean_cost = mean(real_cost),
            se_cost = sd(real_cost)/sqrt(n())) %>% 
  arrange(desc(mean_cost))

transit_cost_by_c %>%
  mutate(country_name = fct_reorder(country_name, mean_cost)) %>% 
ggplot(aes(country_name, mean_cost)) +
geom_errorbar(aes(ymin = mean_cost + qnorm(0.025)*se_cost,
ymax = mean_cost + qnorm(0.975)*se_cost)) +
geom_point(color = "cornflower blue") +
coord_flip()+
  theme_minimal()+
  labs(x = "Country",
       y = "Real Cost (In millions of dollars)",
       title = "Cost to build transit systems vary across countries",
       caption = "Data provided through #tidytuesday by the Transit Costs Project")
```


#Question 2
```{r}
p<- transit_cost_by_c %>%
  mutate(country_name = fct_reorder(country_name, mean_cost)) %>% 
ggplot(aes(country_name, mean_cost)) +
geom_errorbar(aes(ymin = mean_cost + qnorm(0.025)*se_cost,
ymax = mean_cost + qnorm(0.975)*se_cost,
color = "95%"),
width = 0.2,
                size = 0.4) + 
  geom_errorbar(aes(ymin = mean_cost + qnorm(0.05)*se_cost,
                    ymax = mean_cost + qnorm(0.95)*se_cost,
                    color = "90%"),
                width = 0.2,
                size = 0.6) + 
  geom_errorbar(aes(ymin = mean_cost + qnorm(0.1)*se_cost,
                    ymax = mean_cost + qnorm(0.9)*se_cost,
                    color = "80%"),
                width = 0.2,
                size = 0.8)

p + scale_color_manual("Confidence Interval",
                     values = c("#4375D3",
                                lighten("#4375D3", .3),
                                lighten("#4375D3", .6))) +
  geom_point(size = 0.6) +
  coord_flip() 

```


# Question 4

```{r}
# CREATING DATA FRAME/DATA MANIPULATION

q4 <- crime %>% 
  filter(district_id == 1 | district_id == 3 | district_id == 5) %>% 
  filter(offense_category_id == "aggravated-assault" |
           offense_category_id == "other-crimes-against-persons" |
           offense_category_id == "sexual-assault" |
           offense_category_id == "murder")

q4$reported_date <- mdy_hms(q4$reported_date)
q4$reported_date <- as.Date(q4$reported_date)
q4$reported_date <- format(q4$reported_date, "%Y")
q4$offense_category_id <- factor(q4$offense_category_id,
                                 levels = c("aggravated-assault",
                                            "sexual-assault",
                                            "murder",
                                            "other-crimes-against-persons"),
                                 labels = c("Aggravated Assault",
                                            "Sexual Assault",
                                            "Murder",
                                 "Other Crimes Against Persons"))

q4$district_id <- factor(q4$district_id,
                                 labels = c("District 1",
                                            "District 3",
                                            "District 5"))

# CREATING SUMMARY TABLE

q4 %>% 
  dplyr::group_by(reported_date, district_id, offense_category_id) %>% 
  dplyr::summarise(n = n())

sumtab <- q4 %>% 
  count(district_id,offense_category_id, reported_date) %>% 
  pivot_wider(names_from = "reported_date", 
              values_from = "n") 

# GT TABLE CODE

sumtab %>% 
  group_by(district_id) %>% 
  gt() %>% 
  tab_spanner(label = "Year",
              columns = vars('2016', '2017', '2018', '2019', '2020', '2021')) %>%
  cols_label(offense_category_id = "Offense") %>% 
  cols_align(align = "left",
             columns = vars(offense_category_id)) %>% 
  tab_header(
    title = "Crimes Against Persons in Denver: 2014 to Present",
    subtitle = "Sample of three districts"
  ) %>% 
  tab_style(style = cell_text(style = "italic"),
            locations = cells_title(groups = "subtitle"))
  tab_source_note(
    source_note = md("Denver Crime Data Distributed via [Kaggle](https://www.kaggle.com/paultimothymooney/denver-crime-data)")
  )


```

